# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8928617425cdf5955cc50b0120843a0574aca597b04fe7a63ab45669ef0ab2aa2c228280cdd91cc0ac64567b9f4de825cef5d38d63345165872fe9382cddd6b6

test:
  secret_key_base: 480c665ae68155f5ec589a164c807166443211b1847c1917ee8b342e2bfe4956d4468775790c40ec5c66053f3c2eef9b809973e3e2b5ecc8622f5290a378d8b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
